### ISSUE TITLE
Error Deserializing TransactionDetailsApi response (TssV2TransactionsGet200Response)

### ISSUE THREAD

**Issue by AndrewJamesMills** [CyberSource/cybersource-rest-client-dotnet#25] opened 2019-04-09 16:06 UTC
Full error:
Cannot deserialize the current JSON object (e.g. {"name":"value"}) into type 'System.Collections.Generic.List`1
[CyberSource.Model.TssV2TransactionsGet200ResponseMerchantDefinedInformation]' 
because the type requires a JSON array (e.g. [1,2,3]) to deserialize correctly.
To fix this error either change the JSON to a JSON array (e.g. [1,2,3]) or change the deserialized type so that it is a normal .NET type (e.g. not a primitive type like integer, not a collection type like an array or List<T>) that can be deserialized from a JSON object. JsonObjectAttribute can also be added to the type to force it to deserialize from a JSON object.
Path 'merchantDefinedInformation', line 1, position 774.

In the response the merchantDefinedInformation class is null.  The point referred to in the JSON is:
..."fraudMarkingInformation":{},"merchantDefinedInformation":{},"merchantInformation":...

Commenting out the merchantDefinedInformation references in the TssV2TransactionsGet200Response I'm able to retrieve the transaction.

**Comment by gnongsie** [comment] 2019-04-11 09:01
Hi,
We are aware of issues with the Merchant Defined Information section. We have escalated this issue to the relevant team.

Kindly bear with us while the issue is getting resolved. I will keep you updated on this thread.

**Comment by gnongsie** [comment] 2019-08-05 12:14
Hi,

Thank you for bringing this to our attention.

This issue has been addressed in the latest version of the SDK. 
Kindly fetch the SDK from NuGet **(v0.0.0.10)** and check again.

**Comment by snavinch** [comment] 2020-02-06 11:02
Closing this issue as it has been addressed

**Closed by snavinch** 2020-02-06 11:02 UTC
Labels: reported-api-bug
